services:
  backend:
    build:
      context: docker
      args:
        USER_ID: 1000
        GROUP_ID: 1000
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/var/www/html
    environment:
      PHP_DISPLAY_ERRORS: 1

  frontend:
    image: node:20-alpine
    working_dir: /app
    ports:
      - "3000:3000"
    volumes:
      - "./frontend:/app"
    command: "npm run dev"
    tty: true

  database:
    image: mariadb:11.7.2
    ports:
      - "3306:3306"
    environment:
      MARIADB_DATABASE: soluevodb
      MARIADB_ROOT_PASSWORD: 123456
